-- ============================================================
-- JOB AFRICA — MODULE 07 : BASE DE DONNEES ENRICHIE
-- ============================================================
-- A executer dans Supabase SQL Editor
-- ============================================================

-- ============================================================
-- 1. TABLE SOURCES (registre des sources de collecte)
-- ============================================================
create table if not exists public.sources (
    id bigint generated by default as identity primary key,
    nom text not null unique,
    url text,
    type text not null check (type in ('rss', 'html', 'api', 'playwright', 'ats')),
    pays text,
    categorie text,
    actif boolean default true,
    frequence_heures int default 6,
    derniere_collecte timestamptz,
    dernier_statut text,
    nombre_offres_total int default 0,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create index if not exists idx_sources_actif on public.sources(actif);
create index if not exists idx_sources_type on public.sources(type);


-- ============================================================
-- 2. TABLE COMPANIES (entreprises)
-- ============================================================
create table if not exists public.companies (
    id bigint generated by default as identity primary key,
    nom text not null,
    slug text not null unique,
    secteur text,
    taille text,
    site_web text,
    logo_url text,
    description text,
    pays text,
    ville text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create index if not exists idx_companies_slug on public.companies(slug);
create index if not exists idx_companies_secteur on public.companies(secteur);
create index if not exists idx_companies_pays on public.companies(pays);


-- ============================================================
-- 3. TABLE SKILLS (competences normalisees)
-- ============================================================
create table if not exists public.skills (
    id bigint generated by default as identity primary key,
    nom text not null,
    slug text not null unique,
    categorie text,
    alias text[],
    created_at timestamptz default now()
);

create index if not exists idx_skills_slug on public.skills(slug);
create index if not exists idx_skills_categorie on public.skills(categorie);


-- ============================================================
-- 4. AJOUTS A LA TABLE JOBS
-- ============================================================
alter table public.jobs
    add column if not exists company_id bigint references public.companies(id) on delete set null;

alter table public.jobs
    add column if not exists source_id bigint references public.sources(id) on delete set null;

alter table public.jobs
    add column if not exists langue text;

alter table public.jobs
    add column if not exists resume_ia text;

alter table public.jobs
    add column if not exists enriched_at timestamptz;

create index if not exists idx_jobs_company on public.jobs(company_id);
create index if not exists idx_jobs_source on public.jobs(source_id);


-- ============================================================
-- 5. TABLE JOB_SKILLS (relation N-N)
-- ============================================================
create table if not exists public.job_skills (
    id bigint generated by default as identity primary key,
    job_id bigint not null references public.jobs(id) on delete cascade,
    skill_id bigint not null references public.skills(id) on delete cascade,
    score real default 1.0,
    created_at timestamptz default now(),
    unique (job_id, skill_id)
);

create index if not exists idx_job_skills_job on public.job_skills(job_id);
create index if not exists idx_job_skills_skill on public.job_skills(skill_id);


-- ============================================================
-- 6. TABLE USERS (profils utilisateur)
-- ============================================================
create table if not exists public.users (
    id uuid primary key,
    email text not null,
    nom text,
    pays text,
    ville text,
    cv_text text,
    competences text[],
    langue text default 'fr',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create index if not exists idx_users_email on public.users(email);


-- ============================================================
-- 7. TABLE FAVORITES (favoris utilisateur)
-- ============================================================
create table if not exists public.favorites (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users(id) on delete cascade,
    job_id bigint not null references public.jobs(id) on delete cascade,
    note text,
    created_at timestamptz default now(),
    unique (user_id, job_id)
);

create index if not exists idx_favorites_user on public.favorites(user_id);
create index if not exists idx_favorites_job on public.favorites(job_id);


-- ============================================================
-- 8. TABLE ALERTS (alertes email)
-- ============================================================
create table if not exists public.alerts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users(id) on delete cascade,
    nom text not null,
    mots_cles text,
    pays text,
    ville text,
    categorie text,
    type_contrat text,
    teletravail boolean,
    frequence text default 'daily' check (frequence in ('instant', 'daily', 'weekly')),
    actif boolean default true,
    derniere_notification timestamptz,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create index if not exists idx_alerts_user on public.alerts(user_id);
create index if not exists idx_alerts_actif on public.alerts(actif);


-- ============================================================
-- 9. TABLE ALERT_NOTIFICATIONS (historique)
-- ============================================================
create table if not exists public.alert_notifications (
    id bigint generated by default as identity primary key,
    alert_id bigint not null references public.alerts(id) on delete cascade,
    job_id bigint not null references public.jobs(id) on delete cascade,
    envoye boolean default false,
    envoye_at timestamptz,
    erreur text,
    created_at timestamptz default now()
);

create index if not exists idx_notif_alert on public.alert_notifications(alert_id);
create index if not exists idx_notif_envoye on public.alert_notifications(envoye);


-- ============================================================
-- 10. TRIGGERS updated_at
-- ============================================================
create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

do $$
declare t text;
begin
    for t in select unnest(array['sources', 'companies', 'users', 'alerts'])
    loop
        execute format('
            drop trigger if exists trg_%1$s_updated_at on public.%1$s;
            create trigger trg_%1$s_updated_at
            before update on public.%1$s
            for each row execute function public.set_updated_at();
        ', t);
    end loop;
end $$;


-- ============================================================
-- 11. ROW LEVEL SECURITY
-- ============================================================
alter table public.sources enable row level security;
drop policy if exists "sources_public_read" on public.sources;
create policy "sources_public_read"
    on public.sources for select to anon, authenticated using (true);

alter table public.companies enable row level security;
drop policy if exists "companies_public_read" on public.companies;
create policy "companies_public_read"
    on public.companies for select to anon, authenticated using (true);

alter table public.skills enable row level security;
drop policy if exists "skills_public_read" on public.skills;
create policy "skills_public_read"
    on public.skills for select to anon, authenticated using (true);

alter table public.job_skills enable row level security;
drop policy if exists "job_skills_public_read" on public.job_skills;
create policy "job_skills_public_read"
    on public.job_skills for select to anon, authenticated using (true);

alter table public.users enable row level security;
drop policy if exists "users_self_all" on public.users;
create policy "users_self_all"
    on public.users for all to authenticated
    using (auth.uid() = id)
    with check (auth.uid() = id);

alter table public.favorites enable row level security;
drop policy if exists "favorites_self_all" on public.favorites;
create policy "favorites_self_all"
    on public.favorites for all to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

alter table public.alerts enable row level security;
drop policy if exists "alerts_self_all" on public.alerts;
create policy "alerts_self_all"
    on public.alerts for all to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

alter table public.alert_notifications enable row level security;
drop policy if exists "notif_self_read" on public.alert_notifications;
create policy "notif_self_read"
    on public.alert_notifications for select to authenticated
    using (
        exists (
            select 1 from public.alerts a
            where a.id = alert_notifications.alert_id
            and a.user_id = auth.uid()
        )
    );


-- ============================================================
-- 12. VUES STATISTIQUES
-- ============================================================
create or replace view public.v_stats_pays as
select
    pays,
    count(*) as total_offres,
    count(distinct company_id) as total_entreprises
from public.jobs
where pays is not null
group by pays
order by total_offres desc;

create or replace view public.v_top_skills as
select
    s.id,
    s.nom,
    s.categorie,
    count(js.job_id) as total_offres
from public.skills s
left join public.job_skills js on js.skill_id = s.id
group by s.id, s.nom, s.categorie
order by total_offres desc;


-- ============================================================
-- 13. VERIFICATION
-- ============================================================
select
    'Base enrichie prete' as message,
    (select count(*) from information_schema.tables
     where table_schema = 'public') as total_tables;
