-- ============================================================
-- JOB AFRICA — MODULE 11 : AUTHENTIFICATION & ROLES
-- ============================================================

-- 1. Type de rôle
do $$ begin
    create type public.app_role as enum ('user', 'admin');
exception
    when duplicate_object then null;
end $$;


-- 2. Table user_roles
create table if not exists public.user_roles (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    role public.app_role not null default 'user',
    created_at timestamptz default now(),
    unique (user_id, role)
);

create index if not exists idx_user_roles_user on public.user_roles(user_id);
create index if not exists idx_user_roles_role on public.user_roles(role);


-- 3. Table users (profil etendu)
create table if not exists public.users (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    nom text,
    pays text,
    ville text,
    langue text default 'fr',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create index if not exists idx_users_email on public.users(email);


-- 4. Trigger : créer un profil + rôle par défaut à l'inscription
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    -- Crée le profil
    insert into public.users (id, email, nom)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data->>'nom', split_part(new.email, '@', 1))
    )
    on conflict (id) do nothing;

    -- Crée le rôle par défaut
    insert into public.user_roles (user_id, role)
    values (new.id, 'user')
    on conflict (user_id, role) do nothing;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();


-- 5. RLS sur user_roles
alter table public.user_roles enable row level security;

drop policy if exists "users_read_own_roles" on public.user_roles;
create policy "users_read_own_roles"
    on public.user_roles for select
    to authenticated
    using (auth.uid() = user_id);


-- 6. RLS sur users (déjà existant mais on renforce)
alter table public.users enable row level security;

drop policy if exists "users_self_read" on public.users;
create policy "users_self_read"
    on public.users for select
    to authenticated
    using (auth.uid() = id);

drop policy if exists "users_self_update" on public.users;
create policy "users_self_update"
    on public.users for update
    to authenticated
    using (auth.uid() = id);

drop policy if exists "users_self_insert" on public.users;
create policy "users_self_insert"
    on public.users for insert
    to authenticated
    with check (auth.uid() = id);

drop policy if exists "users_public_read" on public.users;
create policy "users_public_read"
    on public.users for select
    to anon
    using (false);  -- Bloque la lecture publique


-- 7. Fonction pour promouvoir un utilisateur en admin
-- Usage : select promote_to_admin('user@example.com');
create or replace function public.promote_to_admin(user_email text)
returns void
language plpgsql
security definer
as $$
declare
    target_user_id uuid;
begin
    select id into target_user_id
    from auth.users
    where email = user_email;

    if target_user_id is null then
        raise exception 'Utilisateur introuvable : %', user_email;
    end if;

    insert into public.user_roles (user_id, role)
    values (target_user_id, 'admin')
    on conflict (user_id, role) do nothing;

    raise notice 'Utilisateur % promu admin', user_email;
end;
$$;


-- 8. Vérification
select
    'Auth et rôles prêts' as message,
    (select count(*) from public.user_roles) as total_roles,
    (select count(*) from public.users) as total_users;
